language: c
os: osx
osx_image: xcode8
compiler: gcc
env:
- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
before_script:
- git clone https://github.com/sergds/psptoolchain.git
- cd psptoolchain
- ./prepare-mac-os.sh
- brew install sdl doxygen
script: "travis_wait ./toolchain-local.sh"
