language: c
os: linux
dist: xenial
compiler: gcc
env:
- MATRIX_EVAL=""
before_script:
- eval "${MATRIX_EVAL}"
- git clone https://github.com/sergds/psptoolchain.git
- cd psptoolchain
- ./prepare-debian-ubuntu.sh
- sudo apt-get install libsdl-dev doxygen libusb-dev libusb-1.0-0
script: "travis_wait ./toolchain-local.sh"
