language: c
os: osx
osx_image: xcode9
compiler: gcc
env:
- MATRIX_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9"
before_script:
- eval "${MATRIX_EVAL}"
- git clone https://github.com/sergds/psptoolchain.git
- cd psptoolchain
- ./prepare-mac-os.sh
- brew install sdl doxygen
script: "travis_wait ./toolchain-local.sh"
